name: 🌐 Deploy site to web

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Environment name
      url:
        required: true
        type: string
        description: Deployed site URL
      site_folder:
        required: true
        type: string
        description: Path of local folder with code to upload
      s3_bucket:
        required: true
        type: string
        description: S3 bucket name
      cdn_resource_id:
        required: true
        type: string
        description: ID of Yandex CDN resource
    secrets:
      yc_sa_json_credentials:
        required: true
      access_key_id:
        required: true
      secret_access_key:
        required: true

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6.0.2

      - name: ⚙️ Setup Bun
        uses: oven-sh/setup-bun@v2.2.0

      - name: ⚙️ Install AWS CLI
        uses: unfor19/install-aws-cli-action@1.0.8
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: 🛠️ Build app
        run: |
          bun install
          bun run check
          bun run build

      - name: 🔼 Upload site
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.access_key_id }} \
          AWS_SECRET_ACCESS_KEY=${{ secrets.secret_access_key }} \
          aws s3 sync "${{ inputs.site_folder }}/" "s3://${{ inputs.s3_bucket }}/" \
            --endpoint-url https://storage.yandexcloud.net \
            --delete --only-show-errors --no-progress
        shell: bash

      - name: 🔑 Get Yandex Cloud IAM token
        id: yc-iam
        uses: yc-actions/yc-iam-token@v1.2.0
        with:
          yc-sa-json-credentials: ${{ secrets.yc_sa_json_credentials }}

      - name: 🔃 Purge CDN cache
        env:
          IAM_TOKEN: ${{ steps.yc-iam.outputs.token }}
          CDN_RESOURCE_ID: ${{ inputs.cdn_resource_id }}
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer $IAM_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"paths":["/*"]}' \
            "https://cdn.api.cloud.yandex.net/cdn/v1/cache/$CDN_RESOURCE_ID:purge"
        shell: bash

      - name: 🏁 Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ github.token }}
          initial-status: success
          environment-url: ${{ inputs.url }}
          environment: ${{ inputs.environment }}
